Feature/vapid authentication
tuvistavie/elixir-web-push-encryption pull request #6
Opened 2018-04-04 15:14 UTC by arjan

Based on the [web-push javascript vapid implementation](https://github.com/web-push-libs/web-push/blob/master/src/vapid-helper.js), I added VAPID authentication, which works on modern Chrome and Firefox browsers. 

This fixes #1.

2018-04-04 17:47 UTC, arjan commented
I see that this PR is not in good shape, I'll update the PR soon

2018-04-05 03:48 UTC, danhper requested changes
Thank you very much for the PR.
It seems you forgot a `IO.inspect`, otherwise LGTM!

2018-04-05 03:48 UTC, tuvistavie commented on lib/web_push_encryption/push.ex
> +    IO.inspect headers, label: "headers"
I suppose this was for debugging purpose?

2018-04-05 06:58 UTC, arjan commented
You're right, that was a leftover. Fixed it!

2018-04-06 03:41 UTC, merged

2018-04-06 03:41 UTC, tuvistavie commented
Thank you very much!

2018-04-06 08:54 UTC, arjan commented
Awesome, would you mind releasing a new version to hex.pm?

2018-04-06 09:13 UTC, tuvistavie commented
Just released as 0.2.0, thanks again for the PR!